version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: parking-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_strong_password123"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Your_strong_password123 -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parking-api
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:8080"
      Database__Provider: "SqlServer"
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=ParkingDb;User Id=sa;Password=Your_strong_password123;TrustServerCertificate=True;"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
