name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore Parking.sln

      - name: Verify formatting
        run: dotnet format Parking.sln --verify-no-changes

      - name: Build
        run: dotnet build Parking.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test Parking.sln --configuration Release --no-build --verbosity normal
