name: CI

on:
  pull_request:

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  build:
    name: Build
    needs: lint
    uses: ./.github/workflows/build.yml
    secrets: inherit

  test:
    name: Testes
    needs: build
    uses: ./.github/workflows/test.yml
    secrets: inherit
