name: Lint

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        id: lint_restore
        run: |
          start=$(date +%s)
          dotnet restore Parking.sln
          end=$(date +%s)
          duration=$((end - start))
          printf "duration=%02d:%02d\n" $((duration/60)) $((duration%60)) >> "$GITHUB_OUTPUT"

      - name: Verificar formatação
        id: format_check
        run: |
          start=$(date +%s)
          dotnet format Parking.sln --verify-no-changes
          end=$(date +%s)
          duration=$((end - start))
          printf "duration=%02d:%02d\n" $((duration/60)) $((duration%60)) >> "$GITHUB_OUTPUT"

      - name: Publicar resumo
        if: always()
        env:
          RESTORE_DURATION: ${{ steps.lint_restore.outputs.duration }}
          RESTORE_OUTCOME: ${{ steps.lint_restore.outcome }}
          FORMAT_DURATION: ${{ steps.format_check.outputs.duration }}
          FORMAT_OUTCOME: ${{ steps.format_check.outcome }}
        run: |
          icon() {
            case "$1" in
              success) printf '✅' ;;
              failure) printf '❌' ;;
              cancelled|skipped) printf '⚠️' ;;
              *) printf '⚠️' ;;
            esac
          }

          restore_icon=$(icon "$RESTORE_OUTCOME")
          format_icon=$(icon "$FORMAT_OUTCOME")

          {
            echo "### Lint"
            echo ""
            echo "| Descrição | Tempo | Resultado |"
            echo "| --- | --- | --- |"
            echo "| Restore | ${RESTORE_DURATION:-N/A} | ${restore_icon} |"
            echo "| dotnet format | ${FORMAT_DURATION:-N/A} | ${format_icon} |"
          } >> "$GITHUB_STEP_SUMMARY"
